export const categoreis = [
  { title: "Коляски 2 в 1", value: 10 },
  { title: "Коляски 3 в 1", value: 11 },
  { title: "Коляски для двійні", value: 12 },
  { title: "Прогулянкові каляски", value: 13 },
  { title: "Автокрісло 0-13кг", value: 20 },
  { title: "Автокрісло 0-18кг", value: 21 },
  { title: "Автокрісло 0-25кг", value: 22 },
  { title: "Автокрісло 0-36кг", value: 23 },
  { title: "Автокрісло 9-36кг", value: 24 },
  { title: "Автокрісло 15-36кг", value: 25 },
  { title: "Ліжечка", value: 30 },
  { title: "Пеленальні комоди", value: 31 },
  { title: "Матраци в ліжечко", value: 32 },
  { title: "Постільна білизна", value: 33 },
  { title: "Конверти для калясок", value: 40 },
  { title: "Кокони та подушки", value: 41 },
  { title: "Муфта-рукавички", value: 42 },
  { title: "Аксесуари для калясок", value: 43 },
  { title: "Гойдалки", value: 50 },
  { title: "Ходунці", value: 51 },
  { title: "Манежі", value: 52 },
  { title: "Велосипеди", value: 53 },
  { title: "Пеленальні дошки", value: 60 },
  { title: "Стілці для годування", value: 61 },
];
